version: "3.7"

services:
  mini-api-service:
    build: .
    ports:
      - 1323:1323
    restart: on-failure
    networks:
      - my-network
    depends_on:
      - mariadb-service

  mariadb-service:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306
    volumes:
      - /home/nadir/minivolume:/var/lib/mysql
      - ./mariadb/schema.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
